- type: job
  parent: CMJobBase
  id: CMResearcher
  name: cm-job-name-researcher
  description: cm-job-description-researcher
  setPreference: false
  playTimeTracker: CMJobResearcher
  startingGear: CMGearResearcher
  icon: "CMJobIconResearcher"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-cmo
  accessGroups:
  - Researcher
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillEndurance: 1
        RMCSkillFirearms: 0
        RMCSkillIntel: 1
        RMCSkillMedical: 3
        RMCSkillResearch: 1
        RMCSkillSurgery: 2
    - type: RMCUserBulkyArmorIncapable
    - type: NpcFactionMember
      factions:
      - WeYa
      - UNMC
    - type: JobPrefix
      prefix: cm-job-prefix-researcher
    - type: ViewIntelObjectives
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: researcher
      background:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: background_medical
    - type: MutinyEligible
  hidden: true # TODO RMC14

- type: startingGear
  id: CMGearResearcher
  equipment:
    jumpsuit: CMJumpsuitResearch
    shoes: RMCShoesLaceup
    id: CMIDCardResearcher # TODO ID has both Marine and WeYa IFF
    # TODO RMC14 random chemical synthesis note, syringe,

- type: startingGear
  id: CMGearResearcherEquipped
  equipment:
    jumpsuit: CMJumpsuitResearch
    gloves: CMHandsLatex
    shoes: RMCShoesLaceup
    id: CMIDCardResearcher
    ears: CMHeadsetResearcher

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointResearcher
  name: researcher spawn point
  components:
  - type: SpawnPoint
    job_id: CMResearcher
  - type: Sprite
    state: res_spawn

- type: playTimeTracker
  id: CMJobResearcher
  isHumanoid: true
