- type: job
  parent: CMJobBase
  id: AU14JobGOVFORSectionSergeantCMBCIU
  name: Unit Leader
  description: au14-job-description-govforSSG
  setPreference: false
  playTimeTracker: AU14JobGOVFORSectionSergeantCMBCIU
  ranks:
    AU14RankCMBChiefDeputy: []
  startingGear: AU14GearGOVFORSectionSergeant
  dummyStartingGear: AU14GearGOVFORPlatoonSergantDummy
  icon: "AU14JobIconPlatoonSarge"
  requireAdminNotify: true
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - augovforcommand
  overwatchSortPriority: -6
  overwatchShowName: true
  overwatchRoleName: Platoon Sergeant
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillConstruction: 2
        RMCSkillCqc: 1
        RMCSkillEndurance: 2
        RMCSkillEngineer: 3
        RMCSkillFirearms: 1
        RMCSkillFireman: 1
        RMCSkillIntel: 1
        RMCSkillJtac: 2
        RMCSkillLeadership: 1
        RMCSkillMedical: 1
        RMCSkillVehicles: 1
        RMCSkillPolice: 1
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORSectionSergeantCMBCIU
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
    - type: MarineOrders
  hidden: false

- type: playTimeTracker
  id: AU14JobGOVFORSectionSergeantCMBCIU
  isHumanoid: true