- type: job
  parent: CMJobBase
  id: AU14JobGOVFORPlatoonCorpsmanCMBCIU
  name: Tactical Medic
  description: au14-job-description-govforplatooncorpsman
  setPreference: false
  playTimeTracker: AU14JobGOVFORPlatoonCorpsmanCMBCIU
  ranks:
    AU14RankCMBSrDeputy:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORPlatoonCorpsmanCMBCIU
      time: 1800 # 30 hours
    AU14RankCMBDeputy: []
  startingGear: AU14GearGOVFORPlatoonCorpsman
  dummyStartingGear: AU14GearGOVFORCorpsmanDummy
  icon: "AU14JobIconCorpsman"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - HospitalCorpsman
  overwatchSortPriority: -2
  overwatchRoleName: Hospital Corpsmen
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFirearms: 1
        RMCSkillFireman: 1
        RMCSkillJtac: 1
        RMCSkillMedical: 2
        RMCSkillSurgery: 1
        RMCSkillConstruction: 2
        RMCSkillEngineer: 3
        RMCSkillPolice: 1
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORPlatoonCorpsmanCMBCIU
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
  hidden: false

- type: playTimeTracker
  id: AU14JobGOVFORPlatoonCorpsmanCMBCIU
  isHumanoid: true