- type: job
  parent: CMJobXenoBase
  id: CMXenoQueen
  name: cm-job-name-xeno-queen
  setPreference: false
  playTimeTracker: CMJobXenoQueen
  requirements:
  - !type:TotalJobsTimeRequirement
    group: CMJobsXeno
    time: 36000 # 10 hours
  - !type:TotalJobsTimeRequirement
    group: CMJobsXenoDrones
    time: 18000 # 5 hours
  - !type:TotalJobsTimeRequirement
    group: CMJobsXenoTierThree
    time: 10800 # 3 hours
  weight: 100
  requireAdminNotify: true
  hidden: false
  supervisors: nobody
  jobPreviewEntity: RMCPlayerXenoQueenPreview
  accessGroups:
  - CMAccessXeno
  - CMAccessXenoQueen

- type: playTimeTracker
  id: CMJobXenoQueen
  isXeno: true

- type: entity
  id: RMCPlayerXenoQueenPreview
  categories: [ HideSpawnMenu ]
  components:
  - type: Sprite
    sprite: _CMU14/Mobs/Xenos/Queen/queen.rsi
    layers:
    - state: alive
      scale: 0.5, 0.5
