# enlisted
- type: rank
  id: RMC_Recruit
  name: Recruit
  prefix: Rct.
  paygrade: E1

- type: rank
  id: RMC_Marine
  name: Marine
  prefix: Mne.
  paygrade: E2

- type: rank
  id: RMC_LanceCorporal
  name: Lance Corporal
  prefix: LCpl.
  paygrade: E3

- type: rank
  id: RMC_Corporal
  name: Corporal
  prefix: Cpl.
  paygrade: E4

- type: rank
  id: RMC_Sergeant
  name: Sergeant
  prefix: Sgt.
  paygrade: E5

- type: rank
  id: RMC_ColourSergeant
  name: Colour Sergeant
  prefix: CSgt.
  paygrade: E7

#  warrant Officers
- type: rank
  id: RMC_WarrantOfficer2
  name: Warrant Officer Class 2
  prefix: WO2.
  paygrade: W1

- type: rank
  id: RMC_WarrantOfficer1
  name: Warrant Officer Class 1
  prefix: WO1.
  paygrade: W2

# officers
- type: rank
  id: RMC_OfficerCader
  name: Officer Cadet
  prefix: OCdt.

- type: rank
  id: RMC_2Lieutenant
  name: Second Lieutenant
  prefix: 2Lt.
  paygrade: O1

- type: rank
  id: RMC_Lieutenant
  name: Lieutenant
  prefix: Lt.
  paygrade: O2

- type: rank
  id: RMC_Captain
  name: Captain
  prefix: Capt.
  paygrade: O3

#field officers
- type: rank
  id: RMC_Major
  name: Major
  prefix: Maj.
  paygrade: O4

- type: rank
  id: RMC_LieutenantColonel
  name: Lieutenant Colonel
  prefix: Lt Col.
  paygrade: O5

- type: rank
  id: RMC_Colonel
  name: Colonel
  prefix: Col.
  paygrade: O6

- type: rank
  id: RMC_Brigadier
  name: Brigadier
  prefix: Brig.
  paygrade: O7

- type: rank
  id: RMC_CommandantDeputy
  name: Deputy Commandant General
  prefix: DCG.
  paygrade: O7

# Generals
- type: rank
  id: RMC_MajorGeneral
  name: Major-General
  prefix: GenMaj.
  paygrade: O8

- type: rank
  id: RMC_LieutenantGeneral
  name: Lieutenant-General
  prefix: Lt Gen.
  paygrade: O9

- type: rank
  id: RMC_General
  name: General
  prefix: Gen.
  paygrade: O10

- type: rank
  id: RMC_CommandantGeneral
  name: Commandant General Royal Marines
  prefix: CGRM.
  paygrade: O10

- type: rank
  id: RMC_CaptainGeneral
  name: Captain General Royal Marines
  prefix: Capt-Gen.