- type: job
  parent: CMJobBase
  id: AU14JobOpforPlatOp
  name: au14-job-name-opforplatop
  description: au14-job-description-opforplatop
  setPreference: true
  canBeAntag: false
  playTimeTracker: AU14JobOpforPlatOp
  ranks:
    RMCRankSecondLT: []
  startingGear: AU14GearopforPlatOp
  dummyStartingGear: AU14GearopforPlatOpDummy
  icon: "AU14JobIconOPFOROpsOfc"
  requireAdminNotify: true
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-opfor
  accessGroups:
  - AU14OpforCommand
  roleWeight: 0.25
  special:

  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - OPFOR
    - type: Marine
      Faction: opfor
    - type: Skills
      skills:
        RMCSkillCqc: 2
        RMCSkillConstruction: 2
        RMCSkillEndurance: 2
        RMCSkillEngineer: 2
        RMCSkillFirearms: 2
        RMCSkillFireman: 2
        RMCSkillIntel: 2
        RMCSkillJtac: 4
        RMCSkillLeadership: 3
        RMCSkillMedical: 3
        RMCSkillNavigations: 1
        RMCSkillOverwatch: 1
        RMCSkillPolice: 2
        RMCSkillPowerLoader: 2
        RMCSkillSurgery: 1
        RMCSkillVehicles: 1
    - type: JobPrefix
      prefix: au14-job-prefix-opforplatop
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
  hidden: false

- type: startingGear
  id: AU14GearopforPlatOp
  equipment:
    id: AU14IDCardopforPlatOp
    ears: AU14HeadsetSectionLeaderopfor

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointopforPlatOp
  name: Spawn Point opfor Platoon Operations Officer
  components:
  - type: SpawnPoint
    job_id: AU14JobOpforPlatOp
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobOpforPlatOp
  isHumanoid: true

- type: startingGear
  id: AU14GearopforPlatOpDummy
  equipment:
    shoes: CMBootsBlack
    head: AU14JunglePatrolCap
    jumpsuit: CMJumpsuitXOFormal
    ears: AU14HeadsetSectionLeaderopfor
