- type: department
  parent: CMDepartmentBase
  id: AU14DepartmentThreat
  name:  au-job-name-threat-member
  description: au14-department-threat-description
  color: "#e3ce94"
  roles:
  - AU14JobThreatLeader
  - AU14JobThreatMember
  departmentRadio: null
  headOfDepartment: null

- type: department
  parent: CMDepartmentBase
  id: AU14DepartmentThirdParty
  name: au14-department-third-party
  description: au14-department-third-party-description
  color: "#e3ce94"
  roles:
  - AU14JobThirdPartyLeader
  - AU14JobThirdPartyMember
  departmentRadio: null
  headOfDepartment: null