- type: job
  parent: CMJobBase
  id: AU14JobGOVFORRadioTelephoneOperatorWYPMC
  name: PMC Communications Specialist
  description: au14-job-description-radiotelephoneooerator
  setPreference: false
  playTimeTracker: AU14JobGOVFORRadioTelephoneOperatorWYPMC
  ranks:
    AU14RankWeYuSeniorOperator:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORRadioTelephoneOperatorWYPMC
      time: 1800 # 30 hours
    AU14RankWeYuOperator: []
  startingGear: AU14GearGOVFORRadioTelephoneOperator
  dummyStartingGear: AU14GearGOVFORRadioTelephoneOperatorDummy
  icon: "AU14JobIconRTO"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - FTL
  overwatchSortPriority: -5
  overwatchRoleName: Radio Telephone Operator
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillConstruction: 2
        RMCSkillEngineer: 3
        RMCSkillFirearms: 1
        RMCSkillFireman: 1
        RMCSkillJtac: 3
        RMCSkillPolice: 1
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORRadioTelephoneOperatorWYPMC
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: synth
    - type: MarineOrders
  hidden: false

- type: playTimeTracker
  id: AU14JobGOVFORRadioTelephoneOperatorWYPMC
  isHumanoid: true