- type: job
  parent: CMJobBase
  id: AU14JobGOVFORSquadAutomaticRiflemanRMC
  name: au14-job-name-govforsquadautomaticriflemanRMC
  suffix: RM
  description: au14-job-description-govforsquadautomaticrifleman
  setPreference: true
  playTimeTracker: AU14JobGOVFORSquadAutomaticRiflemanRMC
  ranks:
    RMC_Corporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadAutomaticRifleman
      time: 1800 # 30 hours
    RMC_LanceCorporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadAutomaticRifleman
      time: 900 # 15 hours
    RMC_Marine: []
  startingGear: AU14GearGOVFORSquadAutomaticRifleman
  dummyStartingGear: AU14GearGOVFORAutoRiflemanDummy
  icon: "AU14JobIconAFN"
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - AU14GovforGunner
  overwatchSortPriority: -3
  overwatchShowName: true
  overwatchRoleName: Machinegunner
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: Marine
      Faction: govfor
    - type: Skills
      skills:
        RMCSkillFirearms: 2
        RMCSkillFireman: 1
        RMCSkillJtac: 1
        RMCSkillSmartGun: 1
        RMCSkillConstruction: 2
        RMCSkillEngineer: 3
        RMCSkillPolice: 1
    - type: SquadArmorWearer
    - type: JobPrefix
      prefix: au14-job-prefix-govforsquadautomaticrifleman
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: smartgunner
  hidden: false

- type: playTimeTracker
  id: AU14JobGOVFORSquadAutomaticRiflemanRMC
  isHumanoid: true